// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinishReason int32

const (
	FinishReason_FINISH_REASON_UNSPECIFIED       FinishReason = 0
	FinishReason_FINISH_REASON_END_TURN          FinishReason = 1
	FinishReason_FINISH_REASON_STOP              FinishReason = 2
	FinishReason_FINISH_REASON_CANCELED          FinishReason = 3
	FinishReason_FINISH_REASON_ERROR             FinishReason = 4
	FinishReason_FINISH_REASON_PERMISSION_DENIED FinishReason = 5
)

// Enum value maps for FinishReason.
var (
	FinishReason_name = map[int32]string{
		0: "FINISH_REASON_UNSPECIFIED",
		1: "FINISH_REASON_END_TURN",
		2: "FINISH_REASON_STOP",
		3: "FINISH_REASON_CANCELED",
		4: "FINISH_REASON_ERROR",
		5: "FINISH_REASON_PERMISSION_DENIED",
	}
	FinishReason_value = map[string]int32{
		"FINISH_REASON_UNSPECIFIED":       0,
		"FINISH_REASON_END_TURN":          1,
		"FINISH_REASON_STOP":              2,
		"FINISH_REASON_CANCELED":          3,
		"FINISH_REASON_ERROR":             4,
		"FINISH_REASON_PERMISSION_DENIED": 5,
	}
)

func (x FinishReason) Enum() *FinishReason {
	p := new(FinishReason)
	*p = x
	return p
}

func (x FinishReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinishReason) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_proto_enumTypes[0].Descriptor()
}

func (FinishReason) Type() protoreflect.EnumType {
	return &file_v1_common_proto_enumTypes[0]
}

func (x FinishReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinishReason.Descriptor instead.
func (FinishReason) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{0}
}

type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 1
	MessageRole_MESSAGE_ROLE_ASSISTANT   MessageRole = 2
	MessageRole_MESSAGE_ROLE_TOOL        MessageRole = 3
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_USER",
		2: "MESSAGE_ROLE_ASSISTANT",
		3: "MESSAGE_ROLE_TOOL",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_USER":        1,
		"MESSAGE_ROLE_ASSISTANT":   2,
		"MESSAGE_ROLE_TOOL":        3,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_proto_enumTypes[1].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_v1_common_proto_enumTypes[1]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{1}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
		3: "HEALTH_STATUS_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
		"HEALTH_STATUS_UNKNOWN":     3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_v1_common_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{2}
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	NextCursor    string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PaginationResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *PaginationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Content part represents different types of content in messages
type ContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ContentPart_Text
	//	*ContentPart_Binary
	//	*ContentPart_ToolCall
	//	*ContentPart_ToolResult
	//	*ContentPart_Finish
	//	*ContentPart_Reasoning
	Content       isContentPart_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ContentPart) GetContent() isContentPart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ContentPart) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*ContentPart_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentPart) GetBinary() *BinaryContent {
	if x != nil {
		if x, ok := x.Content.(*ContentPart_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *ContentPart) GetToolCall() *ToolCallContent {
	if x != nil {
		if x, ok := x.Content.(*ContentPart_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ContentPart) GetToolResult() *ToolResultContent {
	if x != nil {
		if x, ok := x.Content.(*ContentPart_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ContentPart) GetFinish() *FinishContent {
	if x != nil {
		if x, ok := x.Content.(*ContentPart_Finish); ok {
			return x.Finish
		}
	}
	return nil
}

func (x *ContentPart) GetReasoning() *ReasoningContent {
	if x != nil {
		if x, ok := x.Content.(*ContentPart_Reasoning); ok {
			return x.Reasoning
		}
	}
	return nil
}

type isContentPart_Content interface {
	isContentPart_Content()
}

type ContentPart_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentPart_Binary struct {
	Binary *BinaryContent `protobuf:"bytes,2,opt,name=binary,proto3,oneof"`
}

type ContentPart_ToolCall struct {
	ToolCall *ToolCallContent `protobuf:"bytes,3,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ContentPart_ToolResult struct {
	ToolResult *ToolResultContent `protobuf:"bytes,4,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ContentPart_Finish struct {
	Finish *FinishContent `protobuf:"bytes,5,opt,name=finish,proto3,oneof"`
}

type ContentPart_Reasoning struct {
	Reasoning *ReasoningContent `protobuf:"bytes,6,opt,name=reasoning,proto3,oneof"`
}

func (*ContentPart_Text) isContentPart_Content() {}

func (*ContentPart_Binary) isContentPart_Content() {}

func (*ContentPart_ToolCall) isContentPart_Content() {}

func (*ContentPart_ToolResult) isContentPart_Content() {}

func (*ContentPart_Finish) isContentPart_Content() {}

func (*ContentPart_Reasoning) isContentPart_Content() {}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BinaryContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Base64Data    string                 `protobuf:"bytes,4,opt,name=base64_data,json=base64Data,proto3" json:"base64_data,omitempty"` // Alternative to raw bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryContent) Reset() {
	*x = BinaryContent{}
	mi := &file_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryContent) ProtoMessage() {}

func (x *BinaryContent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryContent.ProtoReflect.Descriptor instead.
func (*BinaryContent) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *BinaryContent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BinaryContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *BinaryContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BinaryContent) GetBase64Data() string {
	if x != nil {
		return x.Base64Data
	}
	return ""
}

type ToolCallContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallContent) Reset() {
	*x = ToolCallContent{}
	mi := &file_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallContent) ProtoMessage() {}

func (x *ToolCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallContent.ProtoReflect.Descriptor instead.
func (*ToolCallContent) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallContent) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ToolResultContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string
	IsError       bool                   `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultContent) Reset() {
	*x = ToolResultContent{}
	mi := &file_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultContent) ProtoMessage() {}

func (x *ToolResultContent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultContent.ProtoReflect.Descriptor instead.
func (*ToolResultContent) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *ToolResultContent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToolResultContent) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *ToolResultContent) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type FinishContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        FinishReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=opencode.v1.FinishReason" json:"reason,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishContent) Reset() {
	*x = FinishContent{}
	mi := &file_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishContent) ProtoMessage() {}

func (x *FinishContent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishContent.ProtoReflect.Descriptor instead.
func (*FinishContent) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *FinishContent) GetReason() FinishReason {
	if x != nil {
		return x.Reason
	}
	return FinishReason_FINISH_REASON_UNSPECIFIED
}

func (x *FinishContent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type ReasoningContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thinking      string                 `protobuf:"bytes,1,opt,name=thinking,proto3" json:"thinking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningContent) Reset() {
	*x = ReasoningContent{}
	mi := &file_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningContent) ProtoMessage() {}

func (x *ReasoningContent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningContent.ProtoReflect.Descriptor instead.
func (*ReasoningContent) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *ReasoningContent) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

// Message represents a conversation message
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          MessageRole            `protobuf:"varint,3,opt,name=role,proto3,enum=opencode.v1.MessageRole" json:"role,omitempty"`
	Parts         []*ContentPart         `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"` // Model ID used for this message
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *Message) GetParts() []*ContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Message) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Message) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// Session represents a conversation session
type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentSessionId  string                 `protobuf:"bytes,2,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	MessageCount     int64                  `protobuf:"varint,4,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	SummaryMessageId string                 `protobuf:"bytes,7,opt,name=summary_message_id,json=summaryMessageId,proto3" json:"summary_message_id,omitempty"`
	Cost             float64                `protobuf:"fixed64,8,opt,name=cost,proto3" json:"cost,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Session) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Session) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Session) GetSummaryMessageId() string {
	if x != nil {
		return x.SummaryMessageId
	}
	return ""
}

func (x *Session) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// File represents a file in the workspace
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *File) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *File) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Attachment represents file attachments to messages
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *Attachment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Attachment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Error details for API responses
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=opencode.v1.HealthStatus" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_v1_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_v1_common_proto protoreflect.FileDescriptor

const file_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/common.proto\x12\vopencode.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\x94\x01\n" +
	"\x12PaginationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\xf3\x02\n" +
	"\vContentPart\x12.\n" +
	"\x04text\x18\x01 \x01(\v2\x18.opencode.v1.TextContentH\x00R\x04text\x124\n" +
	"\x06binary\x18\x02 \x01(\v2\x1a.opencode.v1.BinaryContentH\x00R\x06binary\x12;\n" +
	"\ttool_call\x18\x03 \x01(\v2\x1c.opencode.v1.ToolCallContentH\x00R\btoolCall\x12A\n" +
	"\vtool_result\x18\x04 \x01(\v2\x1e.opencode.v1.ToolResultContentH\x00R\n" +
	"toolResult\x124\n" +
	"\x06finish\x18\x05 \x01(\v2\x1a.opencode.v1.FinishContentH\x00R\x06finish\x12=\n" +
	"\treasoning\x18\x06 \x01(\v2\x1d.opencode.v1.ReasoningContentH\x00R\treasoningB\t\n" +
	"\acontent\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"u\n" +
	"\rBinaryContent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1f\n" +
	"\vbase64_data\x18\x04 \x01(\tR\n" +
	"base64Data\"K\n" +
	"\x0fToolCallContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"\x86\x01\n" +
	"\x11ToolResultContent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\"r\n" +
	"\rFinishContent\x121\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x19.opencode.v1.FinishReasonR\x06reason\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\".\n" +
	"\x10ReasoningContent\x12\x1a\n" +
	"\bthinking\x18\x01 \x01(\tR\bthinking\"\xdf\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12,\n" +
	"\x04role\x18\x03 \x01(\x0e2\x18.opencode.v1.MessageRoleR\x04role\x12.\n" +
	"\x05parts\x18\x04 \x03(\v2\x18.opencode.v1.ContentPartR\x05parts\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\x8a\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11parent_session_id\x18\x02 \x01(\tR\x0fparentSessionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12#\n" +
	"\rmessage_count\x18\x04 \x01(\x03R\fmessageCount\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x03R\x10completionTokens\x12,\n" +
	"\x12summary_message_id\x18\a \x01(\tR\x10summaryMessageId\x12\x12\n" +
	"\x04cost\x18\b \x01(\x01R\x04cost\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf3\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"k\n" +
	"\n" +
	"Attachment\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"Q\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\"\xfd\x01\n" +
	"\x0eHealthResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.opencode.v1.HealthStatusR\x06status\x12B\n" +
	"\adetails\x18\x02 \x03(\v2(.opencode.v1.HealthResponse.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xbb\x01\n" +
	"\fFinishReason\x12\x1d\n" +
	"\x19FINISH_REASON_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FINISH_REASON_END_TURN\x10\x01\x12\x16\n" +
	"\x12FINISH_REASON_STOP\x10\x02\x12\x1a\n" +
	"\x16FINISH_REASON_CANCELED\x10\x03\x12\x17\n" +
	"\x13FINISH_REASON_ERROR\x10\x04\x12#\n" +
	"\x1fFINISH_REASON_PERMISSION_DENIED\x10\x05*u\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_ROLE_ASSISTANT\x10\x02\x12\x15\n" +
	"\x11MESSAGE_ROLE_TOOL\x10\x03*\x82\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x02\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x03B3Z1github.com/opencode-ai/opencode/internal/proto/v1b\x06proto3"

var (
	file_v1_common_proto_rawDescOnce sync.Once
	file_v1_common_proto_rawDescData []byte
)

func file_v1_common_proto_rawDescGZIP() []byte {
	file_v1_common_proto_rawDescOnce.Do(func() {
		file_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_proto_rawDesc), len(file_v1_common_proto_rawDesc)))
	})
	return file_v1_common_proto_rawDescData
}

var file_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_common_proto_goTypes = []any{
	(FinishReason)(0),             // 0: opencode.v1.FinishReason
	(MessageRole)(0),              // 1: opencode.v1.MessageRole
	(HealthStatus)(0),             // 2: opencode.v1.HealthStatus
	(*Pagination)(nil),            // 3: opencode.v1.Pagination
	(*PaginationResponse)(nil),    // 4: opencode.v1.PaginationResponse
	(*ContentPart)(nil),           // 5: opencode.v1.ContentPart
	(*TextContent)(nil),           // 6: opencode.v1.TextContent
	(*BinaryContent)(nil),         // 7: opencode.v1.BinaryContent
	(*ToolCallContent)(nil),       // 8: opencode.v1.ToolCallContent
	(*ToolResultContent)(nil),     // 9: opencode.v1.ToolResultContent
	(*FinishContent)(nil),         // 10: opencode.v1.FinishContent
	(*ReasoningContent)(nil),      // 11: opencode.v1.ReasoningContent
	(*Message)(nil),               // 12: opencode.v1.Message
	(*Session)(nil),               // 13: opencode.v1.Session
	(*File)(nil),                  // 14: opencode.v1.File
	(*Attachment)(nil),            // 15: opencode.v1.Attachment
	(*ErrorDetail)(nil),           // 16: opencode.v1.ErrorDetail
	(*HealthResponse)(nil),        // 17: opencode.v1.HealthResponse
	nil,                           // 18: opencode.v1.HealthResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_v1_common_proto_depIdxs = []int32{
	6,  // 0: opencode.v1.ContentPart.text:type_name -> opencode.v1.TextContent
	7,  // 1: opencode.v1.ContentPart.binary:type_name -> opencode.v1.BinaryContent
	8,  // 2: opencode.v1.ContentPart.tool_call:type_name -> opencode.v1.ToolCallContent
	9,  // 3: opencode.v1.ContentPart.tool_result:type_name -> opencode.v1.ToolResultContent
	10, // 4: opencode.v1.ContentPart.finish:type_name -> opencode.v1.FinishContent
	11, // 5: opencode.v1.ContentPart.reasoning:type_name -> opencode.v1.ReasoningContent
	0,  // 6: opencode.v1.FinishContent.reason:type_name -> opencode.v1.FinishReason
	19, // 7: opencode.v1.FinishContent.time:type_name -> google.protobuf.Timestamp
	1,  // 8: opencode.v1.Message.role:type_name -> opencode.v1.MessageRole
	5,  // 9: opencode.v1.Message.parts:type_name -> opencode.v1.ContentPart
	19, // 10: opencode.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	19, // 11: opencode.v1.Message.updated_at:type_name -> google.protobuf.Timestamp
	19, // 12: opencode.v1.Message.finished_at:type_name -> google.protobuf.Timestamp
	19, // 13: opencode.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	19, // 14: opencode.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	19, // 15: opencode.v1.File.created_at:type_name -> google.protobuf.Timestamp
	19, // 16: opencode.v1.File.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 17: opencode.v1.HealthResponse.status:type_name -> opencode.v1.HealthStatus
	18, // 18: opencode.v1.HealthResponse.details:type_name -> opencode.v1.HealthResponse.DetailsEntry
	19, // 19: opencode.v1.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_common_proto_init() }
func file_v1_common_proto_init() {
	if File_v1_common_proto != nil {
		return
	}
	file_v1_common_proto_msgTypes[2].OneofWrappers = []any{
		(*ContentPart_Text)(nil),
		(*ContentPart_Binary)(nil),
		(*ContentPart_ToolCall)(nil),
		(*ContentPart_ToolResult)(nil),
		(*ContentPart_Finish)(nil),
		(*ContentPart_Reasoning)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_proto_rawDesc), len(file_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_proto_goTypes,
		DependencyIndexes: file_v1_common_proto_depIdxs,
		EnumInfos:         file_v1_common_proto_enumTypes,
		MessageInfos:      file_v1_common_proto_msgTypes,
	}.Build()
	File_v1_common_proto = out.File
	file_v1_common_proto_goTypes = nil
	file_v1_common_proto_depIdxs = nil
}
