// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/opencode_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChangeType int32

const (
	FileChangeType_FILE_CHANGE_TYPE_UNSPECIFIED FileChangeType = 0
	FileChangeType_FILE_CHANGE_TYPE_CREATED     FileChangeType = 1
	FileChangeType_FILE_CHANGE_TYPE_MODIFIED    FileChangeType = 2
	FileChangeType_FILE_CHANGE_TYPE_DELETED     FileChangeType = 3
)

// Enum value maps for FileChangeType.
var (
	FileChangeType_name = map[int32]string{
		0: "FILE_CHANGE_TYPE_UNSPECIFIED",
		1: "FILE_CHANGE_TYPE_CREATED",
		2: "FILE_CHANGE_TYPE_MODIFIED",
		3: "FILE_CHANGE_TYPE_DELETED",
	}
	FileChangeType_value = map[string]int32{
		"FILE_CHANGE_TYPE_UNSPECIFIED": 0,
		"FILE_CHANGE_TYPE_CREATED":     1,
		"FILE_CHANGE_TYPE_MODIFIED":    2,
		"FILE_CHANGE_TYPE_DELETED":     3,
	}
)

func (x FileChangeType) Enum() *FileChangeType {
	p := new(FileChangeType)
	*p = x
	return p
}

func (x FileChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_opencode_service_proto_enumTypes[0].Descriptor()
}

func (FileChangeType) Type() protoreflect.EnumType {
	return &file_v1_opencode_service_proto_enumTypes[0]
}

func (x FileChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileChangeType.Descriptor instead.
func (FileChangeType) EnumDescriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{0}
}

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED        AgentStatus = 0
	AgentStatus_AGENT_STATUS_IDLE               AgentStatus = 1
	AgentStatus_AGENT_STATUS_PROCESSING         AgentStatus = 2
	AgentStatus_AGENT_STATUS_WAITING_PERMISSION AgentStatus = 3
	AgentStatus_AGENT_STATUS_ERROR              AgentStatus = 4
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_IDLE",
		2: "AGENT_STATUS_PROCESSING",
		3: "AGENT_STATUS_WAITING_PERMISSION",
		4: "AGENT_STATUS_ERROR",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED":        0,
		"AGENT_STATUS_IDLE":               1,
		"AGENT_STATUS_PROCESSING":         2,
		"AGENT_STATUS_WAITING_PERMISSION": 3,
		"AGENT_STATUS_ERROR":              4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_opencode_service_proto_enumTypes[1].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_v1_opencode_service_proto_enumTypes[1]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{1}
}

// Health check messages
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{0}
}

// Session messages
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{1}
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ResetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"` // Optional new title
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSessionRequest) Reset() {
	*x = ResetSessionRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSessionRequest) ProtoMessage() {}

func (x *ResetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSessionRequest.ProtoReflect.Descriptor instead.
func (*ResetSessionRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResetSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ResetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSessionResponse) Reset() {
	*x = ResetSessionResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSessionResponse) ProtoMessage() {}

func (x *ResetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSessionResponse.ProtoReflect.Descriptor instead.
func (*ResetSessionResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSessionStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatsRequest) Reset() {
	*x = GetSessionStatsRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatsRequest) ProtoMessage() {}

func (x *GetSessionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatsRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{5}
}

type GetSessionStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalMessages     int64                  `protobuf:"varint,1,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	UserMessages      int64                  `protobuf:"varint,2,opt,name=user_messages,json=userMessages,proto3" json:"user_messages,omitempty"`
	AssistantMessages int64                  `protobuf:"varint,3,opt,name=assistant_messages,json=assistantMessages,proto3" json:"assistant_messages,omitempty"`
	ToolMessages      int64                  `protobuf:"varint,4,opt,name=tool_messages,json=toolMessages,proto3" json:"tool_messages,omitempty"`
	PromptTokens      int64                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens  int64                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalCost         float64                `protobuf:"fixed64,7,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	LastActivity      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	ModelsUsed        []string               `protobuf:"bytes,9,rep,name=models_used,json=modelsUsed,proto3" json:"models_used,omitempty"`
	CurrentModel      string                 `protobuf:"bytes,10,opt,name=current_model,json=currentModel,proto3" json:"current_model,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSessionStatsResponse) Reset() {
	*x = GetSessionStatsResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatsResponse) ProtoMessage() {}

func (x *GetSessionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatsResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionStatsResponse) GetTotalMessages() int64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *GetSessionStatsResponse) GetUserMessages() int64 {
	if x != nil {
		return x.UserMessages
	}
	return 0
}

func (x *GetSessionStatsResponse) GetAssistantMessages() int64 {
	if x != nil {
		return x.AssistantMessages
	}
	return 0
}

func (x *GetSessionStatsResponse) GetToolMessages() int64 {
	if x != nil {
		return x.ToolMessages
	}
	return 0
}

func (x *GetSessionStatsResponse) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *GetSessionStatsResponse) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *GetSessionStatsResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *GetSessionStatsResponse) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *GetSessionStatsResponse) GetModelsUsed() []string {
	if x != nil {
		return x.ModelsUsed
	}
	return nil
}

func (x *GetSessionStatsResponse) GetCurrentModel() string {
	if x != nil {
		return x.CurrentModel
	}
	return ""
}

// Message messages
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*ContentPart         `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,2,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"` // Optional model override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageRequest) GetParts() []*ContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *SendMessageRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendMessageRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SendMessageResponse_MessageStarted
	//	*SendMessageResponse_ContentDelta
	//	*SendMessageResponse_ToolCallStarted
	//	*SendMessageResponse_ToolCallCompleted
	//	*SendMessageResponse_MessageCompleted
	//	*SendMessageResponse_Error
	Response      isSendMessageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageResponse) GetResponse() isSendMessageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SendMessageResponse) GetMessageStarted() *MessageStarted {
	if x != nil {
		if x, ok := x.Response.(*SendMessageResponse_MessageStarted); ok {
			return x.MessageStarted
		}
	}
	return nil
}

func (x *SendMessageResponse) GetContentDelta() *ContentDelta {
	if x != nil {
		if x, ok := x.Response.(*SendMessageResponse_ContentDelta); ok {
			return x.ContentDelta
		}
	}
	return nil
}

func (x *SendMessageResponse) GetToolCallStarted() *ToolCallStarted {
	if x != nil {
		if x, ok := x.Response.(*SendMessageResponse_ToolCallStarted); ok {
			return x.ToolCallStarted
		}
	}
	return nil
}

func (x *SendMessageResponse) GetToolCallCompleted() *ToolCallCompleted {
	if x != nil {
		if x, ok := x.Response.(*SendMessageResponse_ToolCallCompleted); ok {
			return x.ToolCallCompleted
		}
	}
	return nil
}

func (x *SendMessageResponse) GetMessageCompleted() *MessageCompleted {
	if x != nil {
		if x, ok := x.Response.(*SendMessageResponse_MessageCompleted); ok {
			return x.MessageCompleted
		}
	}
	return nil
}

func (x *SendMessageResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*SendMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSendMessageResponse_Response interface {
	isSendMessageResponse_Response()
}

type SendMessageResponse_MessageStarted struct {
	MessageStarted *MessageStarted `protobuf:"bytes,1,opt,name=message_started,json=messageStarted,proto3,oneof"`
}

type SendMessageResponse_ContentDelta struct {
	ContentDelta *ContentDelta `protobuf:"bytes,2,opt,name=content_delta,json=contentDelta,proto3,oneof"`
}

type SendMessageResponse_ToolCallStarted struct {
	ToolCallStarted *ToolCallStarted `protobuf:"bytes,3,opt,name=tool_call_started,json=toolCallStarted,proto3,oneof"`
}

type SendMessageResponse_ToolCallCompleted struct {
	ToolCallCompleted *ToolCallCompleted `protobuf:"bytes,4,opt,name=tool_call_completed,json=toolCallCompleted,proto3,oneof"`
}

type SendMessageResponse_MessageCompleted struct {
	MessageCompleted *MessageCompleted `protobuf:"bytes,5,opt,name=message_completed,json=messageCompleted,proto3,oneof"`
}

type SendMessageResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*SendMessageResponse_MessageStarted) isSendMessageResponse_Response() {}

func (*SendMessageResponse_ContentDelta) isSendMessageResponse_Response() {}

func (*SendMessageResponse_ToolCallStarted) isSendMessageResponse_Response() {}

func (*SendMessageResponse_ToolCallCompleted) isSendMessageResponse_Response() {}

func (*SendMessageResponse_MessageCompleted) isSendMessageResponse_Response() {}

func (*SendMessageResponse_Error) isSendMessageResponse_Response() {}

type MessageStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStarted) Reset() {
	*x = MessageStarted{}
	mi := &file_v1_opencode_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStarted) ProtoMessage() {}

func (x *MessageStarted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStarted.ProtoReflect.Descriptor instead.
func (*MessageStarted) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{9}
}

func (x *MessageStarted) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageStarted) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ContentDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentDelta) Reset() {
	*x = ContentDelta{}
	mi := &file_v1_opencode_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentDelta) ProtoMessage() {}

func (x *ContentDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentDelta.ProtoReflect.Descriptor instead.
func (*ContentDelta) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{10}
}

func (x *ContentDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ToolCallStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStarted) Reset() {
	*x = ToolCallStarted{}
	mi := &file_v1_opencode_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStarted) ProtoMessage() {}

func (x *ToolCallStarted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStarted.ProtoReflect.Descriptor instead.
func (*ToolCallStarted) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{11}
}

func (x *ToolCallStarted) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallStarted) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallStarted) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ToolCallCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallCompleted) Reset() {
	*x = ToolCallCompleted{}
	mi := &file_v1_opencode_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallCompleted) ProtoMessage() {}

func (x *ToolCallCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallCompleted.ProtoReflect.Descriptor instead.
func (*ToolCallCompleted) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{12}
}

func (x *ToolCallCompleted) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallCompleted) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolCallCompleted) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type MessageCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FinishReason  FinishReason           `protobuf:"varint,2,opt,name=finish_reason,json=finishReason,proto3,enum=opencode.v1.FinishReason" json:"finish_reason,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCompleted) Reset() {
	*x = MessageCompleted{}
	mi := &file_v1_opencode_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCompleted) ProtoMessage() {}

func (x *MessageCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCompleted.ProtoReflect.Descriptor instead.
func (*MessageCompleted) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{13}
}

func (x *MessageCompleted) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageCompleted) GetFinishReason() FinishReason {
	if x != nil {
		return x.FinishReason
	}
	return FinishReason_FINISH_REASON_UNSPECIFIED
}

func (x *MessageCompleted) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MessageCompleted) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int64                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Cost             float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_v1_opencode_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{14}
}

func (x *TokenUsage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{15}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	RoleFilter    MessageRole            `protobuf:"varint,2,opt,name=role_filter,json=roleFilter,proto3,enum=opencode.v1.MessageRole" json:"role_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListMessagesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMessagesRequest) GetRoleFilter() MessageRole {
	if x != nil {
		return x.RoleFilter
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type StreamMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{18}
}

type StreamMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamMessagesResponse_MessageCreated
	//	*StreamMessagesResponse_MessageUpdated
	//	*StreamMessagesResponse_MessageDeleted
	Event         isStreamMessagesResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesResponse) Reset() {
	*x = StreamMessagesResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesResponse) ProtoMessage() {}

func (x *StreamMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{19}
}

func (x *StreamMessagesResponse) GetEvent() isStreamMessagesResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamMessagesResponse) GetMessageCreated() *MessageCreated {
	if x != nil {
		if x, ok := x.Event.(*StreamMessagesResponse_MessageCreated); ok {
			return x.MessageCreated
		}
	}
	return nil
}

func (x *StreamMessagesResponse) GetMessageUpdated() *MessageUpdated {
	if x != nil {
		if x, ok := x.Event.(*StreamMessagesResponse_MessageUpdated); ok {
			return x.MessageUpdated
		}
	}
	return nil
}

func (x *StreamMessagesResponse) GetMessageDeleted() *MessageDeleted {
	if x != nil {
		if x, ok := x.Event.(*StreamMessagesResponse_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

type isStreamMessagesResponse_Event interface {
	isStreamMessagesResponse_Event()
}

type StreamMessagesResponse_MessageCreated struct {
	MessageCreated *MessageCreated `protobuf:"bytes,1,opt,name=message_created,json=messageCreated,proto3,oneof"`
}

type StreamMessagesResponse_MessageUpdated struct {
	MessageUpdated *MessageUpdated `protobuf:"bytes,2,opt,name=message_updated,json=messageUpdated,proto3,oneof"`
}

type StreamMessagesResponse_MessageDeleted struct {
	MessageDeleted *MessageDeleted `protobuf:"bytes,3,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

func (*StreamMessagesResponse_MessageCreated) isStreamMessagesResponse_Event() {}

func (*StreamMessagesResponse_MessageUpdated) isStreamMessagesResponse_Event() {}

func (*StreamMessagesResponse_MessageDeleted) isStreamMessagesResponse_Event() {}

type MessageCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCreated) Reset() {
	*x = MessageCreated{}
	mi := &file_v1_opencode_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreated) ProtoMessage() {}

func (x *MessageCreated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreated.ProtoReflect.Descriptor instead.
func (*MessageCreated) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{20}
}

func (x *MessageCreated) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdated) Reset() {
	*x = MessageUpdated{}
	mi := &file_v1_opencode_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdated) ProtoMessage() {}

func (x *MessageUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdated.ProtoReflect.Descriptor instead.
func (*MessageUpdated) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{21}
}

func (x *MessageUpdated) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeleted) Reset() {
	*x = MessageDeleted{}
	mi := &file_v1_opencode_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeleted) ProtoMessage() {}

func (x *MessageDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeleted.ProtoReflect.Descriptor instead.
func (*MessageDeleted) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{22}
}

func (x *MessageDeleted) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ClearMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMessagesRequest) Reset() {
	*x = ClearMessagesRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMessagesRequest) ProtoMessage() {}

func (x *ClearMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMessagesRequest.ProtoReflect.Descriptor instead.
func (*ClearMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{23}
}

// File messages
type ListFilesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Path            string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Directory path, empty for workspace root
	Recursive       bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Patterns        []string               `protobuf:"bytes,3,rep,name=patterns,proto3" json:"patterns,omitempty"`                                      // Glob patterns to include
	ExcludePatterns []string               `protobuf:"bytes,4,rep,name=exclude_patterns,json=excludePatterns,proto3" json:"exclude_patterns,omitempty"` // Glob patterns to exclude
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ListFilesRequest) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *ListFilesRequest) GetExcludePatterns() []string {
	if x != nil {
		return x.ExcludePatterns
	}
	return nil
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{25}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,2,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_v1_opencode_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{26}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *FileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{27}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FileInfo      *FileInfo              `protobuf:"bytes,2,opt,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{28}
}

func (x *ReadFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReadFileResponse) GetFileInfo() *FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateDirs    bool                   `protobuf:"varint,3,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"` // Create parent directories if they don't exist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{29}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WriteFileRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileInfo      *FileInfo              `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{30}
}

func (x *WriteFileResponse) GetFileInfo() *FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceVersion  string                 `protobuf:"bytes,1,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"` // Optional: get changes since this version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileChangesRequest) Reset() {
	*x = GetFileChangesRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileChangesRequest) ProtoMessage() {}

func (x *GetFileChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileChangesRequest.ProtoReflect.Descriptor instead.
func (*GetFileChangesRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{32}
}

func (x *GetFileChangesRequest) GetSinceVersion() string {
	if x != nil {
		return x.SinceVersion
	}
	return ""
}

type GetFileChangesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Changes        []*FileChange          `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	CurrentVersion string                 `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFileChangesResponse) Reset() {
	*x = GetFileChangesResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileChangesResponse) ProtoMessage() {}

func (x *GetFileChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileChangesResponse.ProtoReflect.Descriptor instead.
func (*GetFileChangesResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{33}
}

func (x *GetFileChangesResponse) GetChanges() []*FileChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *GetFileChangesResponse) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          FileChangeType         `protobuf:"varint,2,opt,name=type,proto3,enum=opencode.v1.FileChangeType" json:"type,omitempty"`
	OldContent    string                 `protobuf:"bytes,3,opt,name=old_content,json=oldContent,proto3" json:"old_content,omitempty"` // For modified files
	NewContent    string                 `protobuf:"bytes,4,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"` // For modified/created files
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_v1_opencode_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{34}
}

func (x *FileChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChange) GetType() FileChangeType {
	if x != nil {
		return x.Type
	}
	return FileChangeType_FILE_CHANGE_TYPE_UNSPECIFIED
}

func (x *FileChange) GetOldContent() string {
	if x != nil {
		return x.OldContent
	}
	return ""
}

func (x *FileChange) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *FileChange) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Agent messages
type CancelAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAgentRequest) Reset() {
	*x = CancelAgentRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAgentRequest) ProtoMessage() {}

func (x *CancelAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAgentRequest.ProtoReflect.Descriptor instead.
func (*CancelAgentRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{35}
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{36}
}

type GetAgentStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           AgentStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=opencode.v1.AgentStatus" json:"status,omitempty"`
	CurrentOperation string                 `protobuf:"bytes,2,opt,name=current_operation,json=currentOperation,proto3" json:"current_operation,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Model            string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAgentStatusResponse) Reset() {
	*x = GetAgentStatusResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusResponse) ProtoMessage() {}

func (x *GetAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{37}
}

func (x *GetAgentStatusResponse) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *GetAgentStatusResponse) GetCurrentOperation() string {
	if x != nil {
		return x.CurrentOperation
	}
	return ""
}

func (x *GetAgentStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetAgentStatusResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // Optional: filter by provider
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{38}
}

func (x *ListModelsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{39}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider            string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ContextWindow       int32                  `protobuf:"varint,4,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	CostPer_1MInput     float64                `protobuf:"fixed64,5,opt,name=cost_per_1m_input,json=costPer1mInput,proto3" json:"cost_per_1m_input,omitempty"`
	CostPer_1MOutput    float64                `protobuf:"fixed64,6,opt,name=cost_per_1m_output,json=costPer1mOutput,proto3" json:"cost_per_1m_output,omitempty"`
	SupportsAttachments bool                   `protobuf:"varint,7,opt,name=supports_attachments,json=supportsAttachments,proto3" json:"supports_attachments,omitempty"`
	SupportsTools       bool                   `protobuf:"varint,8,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"`
	Capabilities        []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_v1_opencode_service_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{40}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelInfo) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *ModelInfo) GetCostPer_1MInput() float64 {
	if x != nil {
		return x.CostPer_1MInput
	}
	return 0
}

func (x *ModelInfo) GetCostPer_1MOutput() float64 {
	if x != nil {
		return x.CostPer_1MOutput
	}
	return 0
}

func (x *ModelInfo) GetSupportsAttachments() bool {
	if x != nil {
		return x.SupportsAttachments
	}
	return false
}

func (x *ModelInfo) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

func (x *ModelInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelRequest) Reset() {
	*x = SetModelRequest{}
	mi := &file_v1_opencode_service_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelRequest) ProtoMessage() {}

func (x *SetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelRequest.ProtoReflect.Descriptor instead.
func (*SetModelRequest) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{41}
}

func (x *SetModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type SetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelInfo             `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelResponse) Reset() {
	*x = SetModelResponse{}
	mi := &file_v1_opencode_service_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelResponse) ProtoMessage() {}

func (x *SetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_opencode_service_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelResponse.ProtoReflect.Descriptor instead.
func (*SetModelResponse) Descriptor() ([]byte, []int) {
	return file_v1_opencode_service_proto_rawDescGZIP(), []int{42}
}

func (x *SetModelResponse) GetModel() *ModelInfo {
	if x != nil {
		return x.Model
	}
	return nil
}

var File_v1_opencode_service_proto protoreflect.FileDescriptor

const file_v1_opencode_service_proto_rawDesc = "" +
	"\n" +
	"\x19v1/opencode_service.proto\x12\vopencode.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fv1/common.proto\"\x0f\n" +
	"\rHealthRequest\"\x13\n" +
	"\x11GetSessionRequest\"D\n" +
	"\x12GetSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.opencode.v1.SessionR\asession\"+\n" +
	"\x13ResetSessionRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"F\n" +
	"\x14ResetSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.opencode.v1.SessionR\asession\"\x18\n" +
	"\x16GetSessionStatsRequest\"\xb1\x03\n" +
	"\x17GetSessionStatsResponse\x12%\n" +
	"\x0etotal_messages\x18\x01 \x01(\x03R\rtotalMessages\x12#\n" +
	"\ruser_messages\x18\x02 \x01(\x03R\fuserMessages\x12-\n" +
	"\x12assistant_messages\x18\x03 \x01(\x03R\x11assistantMessages\x12#\n" +
	"\rtool_messages\x18\x04 \x01(\x03R\ftoolMessages\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x03R\x10completionTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\a \x01(\x01R\ttotalCost\x12?\n" +
	"\rlast_activity\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12\x1f\n" +
	"\vmodels_used\x18\t \x03(\tR\n" +
	"modelsUsed\x12#\n" +
	"\rcurrent_model\x18\n" +
	" \x01(\tR\fcurrentModel\"\x95\x01\n" +
	"\x12SendMessageRequest\x12.\n" +
	"\x05parts\x18\x01 \x03(\v2\x18.opencode.v1.ContentPartR\x05parts\x129\n" +
	"\vattachments\x18\x02 \x03(\v2\x17.opencode.v1.AttachmentR\vattachments\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"\xcb\x03\n" +
	"\x13SendMessageResponse\x12F\n" +
	"\x0fmessage_started\x18\x01 \x01(\v2\x1b.opencode.v1.MessageStartedH\x00R\x0emessageStarted\x12@\n" +
	"\rcontent_delta\x18\x02 \x01(\v2\x19.opencode.v1.ContentDeltaH\x00R\fcontentDelta\x12J\n" +
	"\x11tool_call_started\x18\x03 \x01(\v2\x1c.opencode.v1.ToolCallStartedH\x00R\x0ftoolCallStarted\x12P\n" +
	"\x13tool_call_completed\x18\x04 \x01(\v2\x1e.opencode.v1.ToolCallCompletedH\x00R\x11toolCallCompleted\x12L\n" +
	"\x11message_completed\x18\x05 \x01(\v2\x1d.opencode.v1.MessageCompletedH\x00R\x10messageCompleted\x122\n" +
	"\x05error\x18\x06 \x01(\v2\x1a.opencode.v1.ErrorResponseH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"i\n" +
	"\x0eMessageStarted\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\"\n" +
	"\fContentDelta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"f\n" +
	"\x0fToolCallStarted\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"h\n" +
	"\x11ToolCallCompleted\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"\xda\x01\n" +
	"\x10MessageCompleted\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12>\n" +
	"\rfinish_reason\x18\x02 \x01(\x0e2\x19.opencode.v1.FinishReasonR\ffinishReason\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x05usage\x18\x04 \x01(\v2\x17.opencode.v1.TokenUsageR\x05usage\"r\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x03R\x10completionTokens\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\"W\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\x89\x01\n" +
	"\x13ListMessagesRequest\x127\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x17.opencode.v1.PaginationR\n" +
	"pagination\x129\n" +
	"\vrole_filter\x18\x02 \x01(\x0e2\x18.opencode.v1.MessageRoleR\n" +
	"roleFilter\"\x89\x01\n" +
	"\x14ListMessagesResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.opencode.v1.MessageR\bmessages\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.opencode.v1.PaginationResponseR\n" +
	"pagination\"\x17\n" +
	"\x15StreamMessagesRequest\"\xf9\x01\n" +
	"\x16StreamMessagesResponse\x12F\n" +
	"\x0fmessage_created\x18\x01 \x01(\v2\x1b.opencode.v1.MessageCreatedH\x00R\x0emessageCreated\x12F\n" +
	"\x0fmessage_updated\x18\x02 \x01(\v2\x1b.opencode.v1.MessageUpdatedH\x00R\x0emessageUpdated\x12F\n" +
	"\x0fmessage_deleted\x18\x03 \x01(\v2\x1b.opencode.v1.MessageDeletedH\x00R\x0emessageDeletedB\a\n" +
	"\x05event\"@\n" +
	"\x0eMessageCreated\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.opencode.v1.MessageR\amessage\"@\n" +
	"\x0eMessageUpdated\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.opencode.v1.MessageR\amessage\"/\n" +
	"\x0eMessageDeleted\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x16\n" +
	"\x14ClearMessagesRequest\"\x8b\x01\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12\x1a\n" +
	"\bpatterns\x18\x03 \x03(\tR\bpatterns\x12)\n" +
	"\x10exclude_patterns\x18\x04 \x03(\tR\x0fexcludePatterns\"@\n" +
	"\x11ListFilesResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.opencode.v1.FileInfoR\x05files\"\xaf\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fis_directory\x18\x02 \x01(\bR\visDirectory\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12;\n" +
	"\vmodified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"`\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x122\n" +
	"\tfile_info\x18\x02 \x01(\v2\x15.opencode.v1.FileInfoR\bfileInfo\"a\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_dirs\x18\x03 \x01(\bR\n" +
	"createDirs\"G\n" +
	"\x11WriteFileResponse\x122\n" +
	"\tfile_info\x18\x01 \x01(\v2\x15.opencode.v1.FileInfoR\bfileInfo\"'\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"<\n" +
	"\x15GetFileChangesRequest\x12#\n" +
	"\rsince_version\x18\x01 \x01(\tR\fsinceVersion\"t\n" +
	"\x16GetFileChangesResponse\x121\n" +
	"\achanges\x18\x01 \x03(\v2\x17.opencode.v1.FileChangeR\achanges\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\"\xcd\x01\n" +
	"\n" +
	"FileChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.opencode.v1.FileChangeTypeR\x04type\x12\x1f\n" +
	"\vold_content\x18\x03 \x01(\tR\n" +
	"oldContent\x12\x1f\n" +
	"\vnew_content\x18\x04 \x01(\tR\n" +
	"newContent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x14\n" +
	"\x12CancelAgentRequest\"\x17\n" +
	"\x15GetAgentStatusRequest\"\xc8\x01\n" +
	"\x16GetAgentStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.opencode.v1.AgentStatusR\x06status\x12+\n" +
	"\x11current_operation\x18\x02 \x01(\tR\x10currentOperation\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"/\n" +
	"\x11ListModelsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"D\n" +
	"\x12ListModelsResponse\x12.\n" +
	"\x06models\x18\x01 \x03(\v2\x16.opencode.v1.ModelInfoR\x06models\"\xc8\x02\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12%\n" +
	"\x0econtext_window\x18\x04 \x01(\x05R\rcontextWindow\x12)\n" +
	"\x11cost_per_1m_input\x18\x05 \x01(\x01R\x0ecostPer1mInput\x12+\n" +
	"\x12cost_per_1m_output\x18\x06 \x01(\x01R\x0fcostPer1mOutput\x121\n" +
	"\x14supports_attachments\x18\a \x01(\bR\x13supportsAttachments\x12%\n" +
	"\x0esupports_tools\x18\b \x01(\bR\rsupportsTools\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\",\n" +
	"\x0fSetModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"@\n" +
	"\x10SetModelResponse\x12,\n" +
	"\x05model\x18\x01 \x01(\v2\x16.opencode.v1.ModelInfoR\x05model*\x8d\x01\n" +
	"\x0eFileChangeType\x12 \n" +
	"\x1cFILE_CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FILE_CHANGE_TYPE_CREATED\x10\x01\x12\x1d\n" +
	"\x19FILE_CHANGE_TYPE_MODIFIED\x10\x02\x12\x1c\n" +
	"\x18FILE_CHANGE_TYPE_DELETED\x10\x03*\x9c\x01\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AGENT_STATUS_IDLE\x10\x01\x12\x1b\n" +
	"\x17AGENT_STATUS_PROCESSING\x10\x02\x12#\n" +
	"\x1fAGENT_STATUS_WAITING_PERMISSION\x10\x03\x12\x16\n" +
	"\x12AGENT_STATUS_ERROR\x10\x042\xe5\r\n" +
	"\x0fOpenCodeService\x12R\n" +
	"\x06Health\x12\x1a.opencode.v1.HealthRequest\x1a\x1b.opencode.v1.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12_\n" +
	"\n" +
	"GetSession\x12\x1e.opencode.v1.GetSessionRequest\x1a\x1f.opencode.v1.GetSessionResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/session\x12n\n" +
	"\fResetSession\x12 .opencode.v1.ResetSessionRequest\x1a!.opencode.v1.ResetSessionResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/session/reset\x12t\n" +
	"\x0fGetSessionStats\x12#.opencode.v1.GetSessionStatsRequest\x1a$.opencode.v1.GetSessionStatsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/session/stats\x12h\n" +
	"\vSendMessage\x12\x1f.opencode.v1.SendMessageRequest\x1a .opencode.v1.SendMessageResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/messages0\x01\x12f\n" +
	"\fListMessages\x12 .opencode.v1.ListMessagesRequest\x1a!.opencode.v1.ListMessagesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/messages\x12u\n" +
	"\x0eStreamMessages\x12\".opencode.v1.StreamMessagesRequest\x1a#.opencode.v1.StreamMessagesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/messages/stream0\x01\x12]\n" +
	"\rClearMessages\x12!.opencode.v1.ClearMessagesRequest\x1a\x16.google.protobuf.Empty\"\x11\x82\xd3\xe4\x93\x02\v*\t/messages\x12Z\n" +
	"\tListFiles\x12\x1d.opencode.v1.ListFilesRequest\x1a\x1e.opencode.v1.ListFilesResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/files\x12a\n" +
	"\bReadFile\x12\x1c.opencode.v1.ReadFileRequest\x1a\x1d.opencode.v1.ReadFileResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/files/{path=**}\x12g\n" +
	"\tWriteFile\x12\x1d.opencode.v1.WriteFileRequest\x1a\x1e.opencode.v1.WriteFileResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/files/{path=**}\x12^\n" +
	"\n" +
	"DeleteFile\x12\x1e.opencode.v1.DeleteFileRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/files/{path=**}\x12q\n" +
	"\x0eGetFileChanges\x12\".opencode.v1.GetFileChangesRequest\x1a#.opencode.v1.GetFileChangesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/files/changes\x12`\n" +
	"\vCancelAgent\x12\x1f.opencode.v1.CancelAgentRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/agent/cancel\x12p\n" +
	"\x0eGetAgentStatus\x12\".opencode.v1.GetAgentStatusRequest\x1a#.opencode.v1.GetAgentStatusResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/agent/status\x12^\n" +
	"\n" +
	"ListModels\x12\x1e.opencode.v1.ListModelsRequest\x1a\x1f.opencode.v1.ListModelsResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/models\x12`\n" +
	"\bSetModel\x12\x1c.opencode.v1.SetModelRequest\x1a\x1d.opencode.v1.SetModelResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/agent/modelB3Z1github.com/opencode-ai/opencode/internal/proto/v1b\x06proto3"

var (
	file_v1_opencode_service_proto_rawDescOnce sync.Once
	file_v1_opencode_service_proto_rawDescData []byte
)

func file_v1_opencode_service_proto_rawDescGZIP() []byte {
	file_v1_opencode_service_proto_rawDescOnce.Do(func() {
		file_v1_opencode_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_opencode_service_proto_rawDesc), len(file_v1_opencode_service_proto_rawDesc)))
	})
	return file_v1_opencode_service_proto_rawDescData
}

var file_v1_opencode_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_opencode_service_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_v1_opencode_service_proto_goTypes = []any{
	(FileChangeType)(0),             // 0: opencode.v1.FileChangeType
	(AgentStatus)(0),                // 1: opencode.v1.AgentStatus
	(*HealthRequest)(nil),           // 2: opencode.v1.HealthRequest
	(*GetSessionRequest)(nil),       // 3: opencode.v1.GetSessionRequest
	(*GetSessionResponse)(nil),      // 4: opencode.v1.GetSessionResponse
	(*ResetSessionRequest)(nil),     // 5: opencode.v1.ResetSessionRequest
	(*ResetSessionResponse)(nil),    // 6: opencode.v1.ResetSessionResponse
	(*GetSessionStatsRequest)(nil),  // 7: opencode.v1.GetSessionStatsRequest
	(*GetSessionStatsResponse)(nil), // 8: opencode.v1.GetSessionStatsResponse
	(*SendMessageRequest)(nil),      // 9: opencode.v1.SendMessageRequest
	(*SendMessageResponse)(nil),     // 10: opencode.v1.SendMessageResponse
	(*MessageStarted)(nil),          // 11: opencode.v1.MessageStarted
	(*ContentDelta)(nil),            // 12: opencode.v1.ContentDelta
	(*ToolCallStarted)(nil),         // 13: opencode.v1.ToolCallStarted
	(*ToolCallCompleted)(nil),       // 14: opencode.v1.ToolCallCompleted
	(*MessageCompleted)(nil),        // 15: opencode.v1.MessageCompleted
	(*TokenUsage)(nil),              // 16: opencode.v1.TokenUsage
	(*ErrorResponse)(nil),           // 17: opencode.v1.ErrorResponse
	(*ListMessagesRequest)(nil),     // 18: opencode.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),    // 19: opencode.v1.ListMessagesResponse
	(*StreamMessagesRequest)(nil),   // 20: opencode.v1.StreamMessagesRequest
	(*StreamMessagesResponse)(nil),  // 21: opencode.v1.StreamMessagesResponse
	(*MessageCreated)(nil),          // 22: opencode.v1.MessageCreated
	(*MessageUpdated)(nil),          // 23: opencode.v1.MessageUpdated
	(*MessageDeleted)(nil),          // 24: opencode.v1.MessageDeleted
	(*ClearMessagesRequest)(nil),    // 25: opencode.v1.ClearMessagesRequest
	(*ListFilesRequest)(nil),        // 26: opencode.v1.ListFilesRequest
	(*ListFilesResponse)(nil),       // 27: opencode.v1.ListFilesResponse
	(*FileInfo)(nil),                // 28: opencode.v1.FileInfo
	(*ReadFileRequest)(nil),         // 29: opencode.v1.ReadFileRequest
	(*ReadFileResponse)(nil),        // 30: opencode.v1.ReadFileResponse
	(*WriteFileRequest)(nil),        // 31: opencode.v1.WriteFileRequest
	(*WriteFileResponse)(nil),       // 32: opencode.v1.WriteFileResponse
	(*DeleteFileRequest)(nil),       // 33: opencode.v1.DeleteFileRequest
	(*GetFileChangesRequest)(nil),   // 34: opencode.v1.GetFileChangesRequest
	(*GetFileChangesResponse)(nil),  // 35: opencode.v1.GetFileChangesResponse
	(*FileChange)(nil),              // 36: opencode.v1.FileChange
	(*CancelAgentRequest)(nil),      // 37: opencode.v1.CancelAgentRequest
	(*GetAgentStatusRequest)(nil),   // 38: opencode.v1.GetAgentStatusRequest
	(*GetAgentStatusResponse)(nil),  // 39: opencode.v1.GetAgentStatusResponse
	(*ListModelsRequest)(nil),       // 40: opencode.v1.ListModelsRequest
	(*ListModelsResponse)(nil),      // 41: opencode.v1.ListModelsResponse
	(*ModelInfo)(nil),               // 42: opencode.v1.ModelInfo
	(*SetModelRequest)(nil),         // 43: opencode.v1.SetModelRequest
	(*SetModelResponse)(nil),        // 44: opencode.v1.SetModelResponse
	(*Session)(nil),                 // 45: opencode.v1.Session
	(*timestamppb.Timestamp)(nil),   // 46: google.protobuf.Timestamp
	(*ContentPart)(nil),             // 47: opencode.v1.ContentPart
	(*Attachment)(nil),              // 48: opencode.v1.Attachment
	(FinishReason)(0),               // 49: opencode.v1.FinishReason
	(*Pagination)(nil),              // 50: opencode.v1.Pagination
	(MessageRole)(0),                // 51: opencode.v1.MessageRole
	(*Message)(nil),                 // 52: opencode.v1.Message
	(*PaginationResponse)(nil),      // 53: opencode.v1.PaginationResponse
	(*HealthResponse)(nil),          // 54: opencode.v1.HealthResponse
	(*emptypb.Empty)(nil),           // 55: google.protobuf.Empty
}
var file_v1_opencode_service_proto_depIdxs = []int32{
	45, // 0: opencode.v1.GetSessionResponse.session:type_name -> opencode.v1.Session
	45, // 1: opencode.v1.ResetSessionResponse.session:type_name -> opencode.v1.Session
	46, // 2: opencode.v1.GetSessionStatsResponse.last_activity:type_name -> google.protobuf.Timestamp
	47, // 3: opencode.v1.SendMessageRequest.parts:type_name -> opencode.v1.ContentPart
	48, // 4: opencode.v1.SendMessageRequest.attachments:type_name -> opencode.v1.Attachment
	11, // 5: opencode.v1.SendMessageResponse.message_started:type_name -> opencode.v1.MessageStarted
	12, // 6: opencode.v1.SendMessageResponse.content_delta:type_name -> opencode.v1.ContentDelta
	13, // 7: opencode.v1.SendMessageResponse.tool_call_started:type_name -> opencode.v1.ToolCallStarted
	14, // 8: opencode.v1.SendMessageResponse.tool_call_completed:type_name -> opencode.v1.ToolCallCompleted
	15, // 9: opencode.v1.SendMessageResponse.message_completed:type_name -> opencode.v1.MessageCompleted
	17, // 10: opencode.v1.SendMessageResponse.error:type_name -> opencode.v1.ErrorResponse
	46, // 11: opencode.v1.MessageStarted.timestamp:type_name -> google.protobuf.Timestamp
	49, // 12: opencode.v1.MessageCompleted.finish_reason:type_name -> opencode.v1.FinishReason
	46, // 13: opencode.v1.MessageCompleted.timestamp:type_name -> google.protobuf.Timestamp
	16, // 14: opencode.v1.MessageCompleted.usage:type_name -> opencode.v1.TokenUsage
	50, // 15: opencode.v1.ListMessagesRequest.pagination:type_name -> opencode.v1.Pagination
	51, // 16: opencode.v1.ListMessagesRequest.role_filter:type_name -> opencode.v1.MessageRole
	52, // 17: opencode.v1.ListMessagesResponse.messages:type_name -> opencode.v1.Message
	53, // 18: opencode.v1.ListMessagesResponse.pagination:type_name -> opencode.v1.PaginationResponse
	22, // 19: opencode.v1.StreamMessagesResponse.message_created:type_name -> opencode.v1.MessageCreated
	23, // 20: opencode.v1.StreamMessagesResponse.message_updated:type_name -> opencode.v1.MessageUpdated
	24, // 21: opencode.v1.StreamMessagesResponse.message_deleted:type_name -> opencode.v1.MessageDeleted
	52, // 22: opencode.v1.MessageCreated.message:type_name -> opencode.v1.Message
	52, // 23: opencode.v1.MessageUpdated.message:type_name -> opencode.v1.Message
	28, // 24: opencode.v1.ListFilesResponse.files:type_name -> opencode.v1.FileInfo
	46, // 25: opencode.v1.FileInfo.modified_at:type_name -> google.protobuf.Timestamp
	28, // 26: opencode.v1.ReadFileResponse.file_info:type_name -> opencode.v1.FileInfo
	28, // 27: opencode.v1.WriteFileResponse.file_info:type_name -> opencode.v1.FileInfo
	36, // 28: opencode.v1.GetFileChangesResponse.changes:type_name -> opencode.v1.FileChange
	0,  // 29: opencode.v1.FileChange.type:type_name -> opencode.v1.FileChangeType
	46, // 30: opencode.v1.FileChange.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 31: opencode.v1.GetAgentStatusResponse.status:type_name -> opencode.v1.AgentStatus
	46, // 32: opencode.v1.GetAgentStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	42, // 33: opencode.v1.ListModelsResponse.models:type_name -> opencode.v1.ModelInfo
	42, // 34: opencode.v1.SetModelResponse.model:type_name -> opencode.v1.ModelInfo
	2,  // 35: opencode.v1.OpenCodeService.Health:input_type -> opencode.v1.HealthRequest
	3,  // 36: opencode.v1.OpenCodeService.GetSession:input_type -> opencode.v1.GetSessionRequest
	5,  // 37: opencode.v1.OpenCodeService.ResetSession:input_type -> opencode.v1.ResetSessionRequest
	7,  // 38: opencode.v1.OpenCodeService.GetSessionStats:input_type -> opencode.v1.GetSessionStatsRequest
	9,  // 39: opencode.v1.OpenCodeService.SendMessage:input_type -> opencode.v1.SendMessageRequest
	18, // 40: opencode.v1.OpenCodeService.ListMessages:input_type -> opencode.v1.ListMessagesRequest
	20, // 41: opencode.v1.OpenCodeService.StreamMessages:input_type -> opencode.v1.StreamMessagesRequest
	25, // 42: opencode.v1.OpenCodeService.ClearMessages:input_type -> opencode.v1.ClearMessagesRequest
	26, // 43: opencode.v1.OpenCodeService.ListFiles:input_type -> opencode.v1.ListFilesRequest
	29, // 44: opencode.v1.OpenCodeService.ReadFile:input_type -> opencode.v1.ReadFileRequest
	31, // 45: opencode.v1.OpenCodeService.WriteFile:input_type -> opencode.v1.WriteFileRequest
	33, // 46: opencode.v1.OpenCodeService.DeleteFile:input_type -> opencode.v1.DeleteFileRequest
	34, // 47: opencode.v1.OpenCodeService.GetFileChanges:input_type -> opencode.v1.GetFileChangesRequest
	37, // 48: opencode.v1.OpenCodeService.CancelAgent:input_type -> opencode.v1.CancelAgentRequest
	38, // 49: opencode.v1.OpenCodeService.GetAgentStatus:input_type -> opencode.v1.GetAgentStatusRequest
	40, // 50: opencode.v1.OpenCodeService.ListModels:input_type -> opencode.v1.ListModelsRequest
	43, // 51: opencode.v1.OpenCodeService.SetModel:input_type -> opencode.v1.SetModelRequest
	54, // 52: opencode.v1.OpenCodeService.Health:output_type -> opencode.v1.HealthResponse
	4,  // 53: opencode.v1.OpenCodeService.GetSession:output_type -> opencode.v1.GetSessionResponse
	6,  // 54: opencode.v1.OpenCodeService.ResetSession:output_type -> opencode.v1.ResetSessionResponse
	8,  // 55: opencode.v1.OpenCodeService.GetSessionStats:output_type -> opencode.v1.GetSessionStatsResponse
	10, // 56: opencode.v1.OpenCodeService.SendMessage:output_type -> opencode.v1.SendMessageResponse
	19, // 57: opencode.v1.OpenCodeService.ListMessages:output_type -> opencode.v1.ListMessagesResponse
	21, // 58: opencode.v1.OpenCodeService.StreamMessages:output_type -> opencode.v1.StreamMessagesResponse
	55, // 59: opencode.v1.OpenCodeService.ClearMessages:output_type -> google.protobuf.Empty
	27, // 60: opencode.v1.OpenCodeService.ListFiles:output_type -> opencode.v1.ListFilesResponse
	30, // 61: opencode.v1.OpenCodeService.ReadFile:output_type -> opencode.v1.ReadFileResponse
	32, // 62: opencode.v1.OpenCodeService.WriteFile:output_type -> opencode.v1.WriteFileResponse
	55, // 63: opencode.v1.OpenCodeService.DeleteFile:output_type -> google.protobuf.Empty
	35, // 64: opencode.v1.OpenCodeService.GetFileChanges:output_type -> opencode.v1.GetFileChangesResponse
	55, // 65: opencode.v1.OpenCodeService.CancelAgent:output_type -> google.protobuf.Empty
	39, // 66: opencode.v1.OpenCodeService.GetAgentStatus:output_type -> opencode.v1.GetAgentStatusResponse
	41, // 67: opencode.v1.OpenCodeService.ListModels:output_type -> opencode.v1.ListModelsResponse
	44, // 68: opencode.v1.OpenCodeService.SetModel:output_type -> opencode.v1.SetModelResponse
	52, // [52:69] is the sub-list for method output_type
	35, // [35:52] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_v1_opencode_service_proto_init() }
func file_v1_opencode_service_proto_init() {
	if File_v1_opencode_service_proto != nil {
		return
	}
	file_v1_common_proto_init()
	file_v1_opencode_service_proto_msgTypes[8].OneofWrappers = []any{
		(*SendMessageResponse_MessageStarted)(nil),
		(*SendMessageResponse_ContentDelta)(nil),
		(*SendMessageResponse_ToolCallStarted)(nil),
		(*SendMessageResponse_ToolCallCompleted)(nil),
		(*SendMessageResponse_MessageCompleted)(nil),
		(*SendMessageResponse_Error)(nil),
	}
	file_v1_opencode_service_proto_msgTypes[19].OneofWrappers = []any{
		(*StreamMessagesResponse_MessageCreated)(nil),
		(*StreamMessagesResponse_MessageUpdated)(nil),
		(*StreamMessagesResponse_MessageDeleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_opencode_service_proto_rawDesc), len(file_v1_opencode_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_opencode_service_proto_goTypes,
		DependencyIndexes: file_v1_opencode_service_proto_depIdxs,
		EnumInfos:         file_v1_opencode_service_proto_enumTypes,
		MessageInfos:      file_v1_opencode_service_proto_msgTypes,
	}.Build()
	File_v1_opencode_service_proto = out.File
	file_v1_opencode_service_proto_goTypes = nil
	file_v1_opencode_service_proto_depIdxs = nil
}
