// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: orchestrator/v1/orchestrator.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionState int32

const (
	SessionState_SESSION_STATE_UNKNOWN  SessionState = 0
	SessionState_SESSION_STATE_CREATING SessionState = 1
	SessionState_SESSION_STATE_RUNNING  SessionState = 2
	SessionState_SESSION_STATE_STOPPING SessionState = 3
	SessionState_SESSION_STATE_STOPPED  SessionState = 4
	SessionState_SESSION_STATE_ERROR    SessionState = 5
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNKNOWN",
		1: "SESSION_STATE_CREATING",
		2: "SESSION_STATE_RUNNING",
		3: "SESSION_STATE_STOPPING",
		4: "SESSION_STATE_STOPPED",
		5: "SESSION_STATE_ERROR",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNKNOWN":  0,
		"SESSION_STATE_CREATING": 1,
		"SESSION_STATE_RUNNING":  2,
		"SESSION_STATE_STOPPING": 3,
		"SESSION_STATE_STOPPED":  4,
		"SESSION_STATE_ERROR":    5,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_v1_orchestrator_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_orchestrator_v1_orchestrator_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_v1_orchestrator_proto_enumTypes[1].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_orchestrator_v1_orchestrator_proto_enumTypes[1]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{1, 0}
}

// Health check messages
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=opencode.orchestrator.v1.HealthResponse_Status" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Session management messages
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        *SessionConfig         `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateSessionRequest) GetConfig() *SessionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSessionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int32                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSessionsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteSessionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Proxy messages
type ProxyHTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyHTTPRequest) Reset() {
	*x = ProxyHTTPRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHTTPRequest) ProtoMessage() {}

func (x *ProxyHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHTTPRequest.ProtoReflect.Descriptor instead.
func (*ProxyHTTPRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *ProxyHTTPRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProxyHTTPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProxyHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyHTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyHTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyHTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ProxyHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyHTTPResponse) Reset() {
	*x = ProxyHTTPResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHTTPResponse) ProtoMessage() {}

func (x *ProxyHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHTTPResponse.ProtoReflect.Descriptor instead.
func (*ProxyHTTPResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *ProxyHTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProxyHTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyHTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ProxyStreamRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProxyStreamRequest_Data
	//	*ProxyStreamRequest_Control
	Payload       isProxyStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyStreamRequest) Reset() {
	*x = ProxyStreamRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStreamRequest) ProtoMessage() {}

func (x *ProxyStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStreamRequest.ProtoReflect.Descriptor instead.
func (*ProxyStreamRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *ProxyStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProxyStreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProxyStreamRequest) GetPayload() isProxyStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProxyStreamRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProxyStreamRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ProxyStreamRequest) GetControl() string {
	if x != nil {
		if x, ok := x.Payload.(*ProxyStreamRequest_Control); ok {
			return x.Control
		}
	}
	return ""
}

type isProxyStreamRequest_Payload interface {
	isProxyStreamRequest_Payload()
}

type ProxyStreamRequest_Data struct {
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type ProxyStreamRequest_Control struct {
	Control string `protobuf:"bytes,4,opt,name=control,proto3,oneof"`
}

func (*ProxyStreamRequest_Data) isProxyStreamRequest_Payload() {}

func (*ProxyStreamRequest_Control) isProxyStreamRequest_Payload() {}

type ProxyStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProxyStreamResponse_Data
	//	*ProxyStreamResponse_Error
	Payload       isProxyStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyStreamResponse) Reset() {
	*x = ProxyStreamResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStreamResponse) ProtoMessage() {}

func (x *ProxyStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStreamResponse.ProtoReflect.Descriptor instead.
func (*ProxyStreamResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *ProxyStreamResponse) GetPayload() isProxyStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProxyStreamResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProxyStreamResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ProxyStreamResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*ProxyStreamResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isProxyStreamResponse_Payload interface {
	isProxyStreamResponse_Payload()
}

type ProxyStreamResponse_Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ProxyStreamResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ProxyStreamResponse_Data) isProxyStreamResponse_Payload() {}

func (*ProxyStreamResponse_Error) isProxyStreamResponse_Payload() {}

// Session data structures
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State         SessionState           `protobuf:"varint,4,opt,name=state,proto3,enum=opencode.orchestrator.v1.SessionState" json:"state,omitempty"`
	Config        *SessionConfig         `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Status        *SessionStatus         `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastAccessed  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNKNOWN
}

func (x *Session) GetConfig() *SessionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Session) GetStatus() *SessionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Session) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Session) GetLastAccessed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessed
	}
	return nil
}

type SessionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repository configuration
	Repository *RepositoryConfig `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Environment variables for the development session
	Environment   map[string]string `protobuf:"bytes,2,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *SessionConfig) GetRepository() *RepositoryConfig {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *SessionConfig) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type RepositoryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Git repository URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Branch, tag, or commit to checkout (optional, defaults to main/master)
	Ref           string `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryConfig) Reset() {
	*x = RepositoryConfig{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryConfig) ProtoMessage() {}

func (x *RepositoryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryConfig.ProtoReflect.Descriptor instead.
func (*RepositoryConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *RepositoryConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RepositoryConfig) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type SessionStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PodName          string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace     string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PvcName          string                 `protobuf:"bytes,3,opt,name=pvc_name,json=pvcName,proto3" json:"pvc_name,omitempty"`
	InternalEndpoint string                 `protobuf:"bytes,4,opt,name=internal_endpoint,json=internalEndpoint,proto3" json:"internal_endpoint,omitempty"`
	Ready            bool                   `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	Message          string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ReadyAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ready_at,json=readyAt,proto3" json:"ready_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionStatus) Reset() {
	*x = SessionStatus{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatus) ProtoMessage() {}

func (x *SessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatus.ProtoReflect.Descriptor instead.
func (*SessionStatus) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *SessionStatus) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SessionStatus) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *SessionStatus) GetPvcName() string {
	if x != nil {
		return x.PvcName
	}
	return ""
}

func (x *SessionStatus) GetInternalEndpoint() string {
	if x != nil {
		return x.InternalEndpoint
	}
	return ""
}

func (x *SessionStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *SessionStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SessionStatus) GetReadyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadyAt
	}
	return nil
}

var File_orchestrator_v1_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_v1_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\"orchestrator/v1/orchestrator.proto\x12\x18opencode.orchestrator.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rHealthRequest\"\xef\x02\n" +
	"\x0eHealthResponse\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.opencode.orchestrator.v1.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12O\n" +
	"\adetails\x18\x03 \x03(\v25.opencode.orchestrator.v1.HealthResponse.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\x93\x02\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12R\n" +
	"\x06labels\x18\x03 \x03(\v2:.opencode.orchestrator.v1.CreateSessionRequest.LabelsEntryR\x06labels\x12?\n" +
	"\x06config\x18\x04 \x01(\v2'.opencode.orchestrator.v1.SessionConfigR\x06config\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x15CreateSessionResponse\x12;\n" +
	"\asession\x18\x01 \x01(\v2!.opencode.orchestrator.v1.SessionR\asession\"K\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Q\n" +
	"\x12GetSessionResponse\x12;\n" +
	"\asession\x18\x01 \x01(\v2!.opencode.orchestrator.v1.SessionR\asession\"\x82\x01\n" +
	"\x13ListSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\x9c\x01\n" +
	"\x14ListSessionsResponse\x12=\n" +
	"\bsessions\x18\x01 \x03(\v2!.opencode.orchestrator.v1.SessionR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"d\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x99\x02\n" +
	"\x10ProxyHTTPRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12Q\n" +
	"\aheaders\x18\x05 \x03(\v27.opencode.orchestrator.v1.ProxyHTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\x11ProxyHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12R\n" +
	"\aheaders\x18\x02 \x03(\v28.opencode.orchestrator.v1.ProxyHTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x12ProxyStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04data\x12\x1a\n" +
	"\acontrol\x18\x04 \x01(\tH\x00R\acontrolB\t\n" +
	"\apayload\"N\n" +
	"\x13ProxyStreamResponse\x12\x14\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"\xbf\x04\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12<\n" +
	"\x05state\x18\x04 \x01(\x0e2&.opencode.orchestrator.v1.SessionStateR\x05state\x12?\n" +
	"\x06config\x18\x05 \x01(\v2'.opencode.orchestrator.v1.SessionConfigR\x06config\x12?\n" +
	"\x06status\x18\x06 \x01(\v2'.opencode.orchestrator.v1.SessionStatusR\x06status\x12E\n" +
	"\x06labels\x18\a \x03(\v2-.opencode.orchestrator.v1.Session.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12?\n" +
	"\rlast_accessed\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessed\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\rSessionConfig\x12J\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2*.opencode.orchestrator.v1.RepositoryConfigR\n" +
	"repository\x12Z\n" +
	"\venvironment\x18\x02 \x03(\v28.opencode.orchestrator.v1.SessionConfig.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x10RepositoryConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\"\xfe\x01\n" +
	"\rSessionStatus\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpvc_name\x18\x03 \x01(\tR\apvcName\x12+\n" +
	"\x11internal_endpoint\x18\x04 \x01(\tR\x10internalEndpoint\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x125\n" +
	"\bready_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\areadyAt*\xb0\x01\n" +
	"\fSessionState\x12\x19\n" +
	"\x15SESSION_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATE_CREATING\x10\x01\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16SESSION_STATE_STOPPING\x10\x03\x12\x19\n" +
	"\x15SESSION_STATE_STOPPED\x10\x04\x12\x17\n" +
	"\x13SESSION_STATE_ERROR\x10\x052\xf4\a\n" +
	"\x13OrchestratorService\x12l\n" +
	"\x06Health\x12'.opencode.orchestrator.v1.HealthRequest\x1a(.opencode.orchestrator.v1.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12\x86\x01\n" +
	"\rCreateSession\x12..opencode.orchestrator.v1.CreateSessionRequest\x1a/.opencode.orchestrator.v1.CreateSessionResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/sessions\x12\x87\x01\n" +
	"\n" +
	"GetSession\x12+.opencode.orchestrator.v1.GetSessionRequest\x1a,.opencode.orchestrator.v1.GetSessionResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/sessions/{session_id}\x12\x80\x01\n" +
	"\fListSessions\x12-.opencode.orchestrator.v1.ListSessionsRequest\x1a..opencode.orchestrator.v1.ListSessionsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/sessions\x12w\n" +
	"\rDeleteSession\x12..opencode.orchestrator.v1.DeleteSessionRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/sessions/{session_id}\x12\xef\x01\n" +
	"\tProxyHTTP\x12*.opencode.orchestrator.v1.ProxyHTTPRequest\x1a+.opencode.orchestrator.v1.ProxyHTTPResponse\"\x88\x01\x82\xd3\xe4\x93\x02\x81\x01:\x01*Z\x1e\x12\x1c/sessions/{session_id}/proxyZ\x1e\x1a\x1c/sessions/{session_id}/proxyZ\x1e*\x1c/sessions/{session_id}/proxy\"\x1c/sessions/{session_id}/proxy\x12n\n" +
	"\vProxyStream\x12,.opencode.orchestrator.v1.ProxyStreamRequest\x1a-.opencode.orchestrator.v1.ProxyStreamResponse(\x010\x01B@Z>github.com/opencode-ai/opencode/internal/proto/orchestrator/v1b\x06proto3"

var (
	file_orchestrator_v1_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_v1_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_v1_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_v1_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_v1_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_v1_orchestrator_proto_rawDesc), len(file_orchestrator_v1_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_v1_orchestrator_proto_rawDescData
}

var file_orchestrator_v1_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orchestrator_v1_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_orchestrator_v1_orchestrator_proto_goTypes = []any{
	(SessionState)(0),             // 0: opencode.orchestrator.v1.SessionState
	(HealthResponse_Status)(0),    // 1: opencode.orchestrator.v1.HealthResponse.Status
	(*HealthRequest)(nil),         // 2: opencode.orchestrator.v1.HealthRequest
	(*HealthResponse)(nil),        // 3: opencode.orchestrator.v1.HealthResponse
	(*CreateSessionRequest)(nil),  // 4: opencode.orchestrator.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 5: opencode.orchestrator.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),     // 6: opencode.orchestrator.v1.GetSessionRequest
	(*GetSessionResponse)(nil),    // 7: opencode.orchestrator.v1.GetSessionResponse
	(*ListSessionsRequest)(nil),   // 8: opencode.orchestrator.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 9: opencode.orchestrator.v1.ListSessionsResponse
	(*DeleteSessionRequest)(nil),  // 10: opencode.orchestrator.v1.DeleteSessionRequest
	(*ProxyHTTPRequest)(nil),      // 11: opencode.orchestrator.v1.ProxyHTTPRequest
	(*ProxyHTTPResponse)(nil),     // 12: opencode.orchestrator.v1.ProxyHTTPResponse
	(*ProxyStreamRequest)(nil),    // 13: opencode.orchestrator.v1.ProxyStreamRequest
	(*ProxyStreamResponse)(nil),   // 14: opencode.orchestrator.v1.ProxyStreamResponse
	(*Session)(nil),               // 15: opencode.orchestrator.v1.Session
	(*SessionConfig)(nil),         // 16: opencode.orchestrator.v1.SessionConfig
	(*RepositoryConfig)(nil),      // 17: opencode.orchestrator.v1.RepositoryConfig
	(*SessionStatus)(nil),         // 18: opencode.orchestrator.v1.SessionStatus
	nil,                           // 19: opencode.orchestrator.v1.HealthResponse.DetailsEntry
	nil,                           // 20: opencode.orchestrator.v1.CreateSessionRequest.LabelsEntry
	nil,                           // 21: opencode.orchestrator.v1.ProxyHTTPRequest.HeadersEntry
	nil,                           // 22: opencode.orchestrator.v1.ProxyHTTPResponse.HeadersEntry
	nil,                           // 23: opencode.orchestrator.v1.Session.LabelsEntry
	nil,                           // 24: opencode.orchestrator.v1.SessionConfig.EnvironmentEntry
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 26: google.protobuf.Empty
}
var file_orchestrator_v1_orchestrator_proto_depIdxs = []int32{
	1,  // 0: opencode.orchestrator.v1.HealthResponse.status:type_name -> opencode.orchestrator.v1.HealthResponse.Status
	19, // 1: opencode.orchestrator.v1.HealthResponse.details:type_name -> opencode.orchestrator.v1.HealthResponse.DetailsEntry
	25, // 2: opencode.orchestrator.v1.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	20, // 3: opencode.orchestrator.v1.CreateSessionRequest.labels:type_name -> opencode.orchestrator.v1.CreateSessionRequest.LabelsEntry
	16, // 4: opencode.orchestrator.v1.CreateSessionRequest.config:type_name -> opencode.orchestrator.v1.SessionConfig
	15, // 5: opencode.orchestrator.v1.CreateSessionResponse.session:type_name -> opencode.orchestrator.v1.Session
	15, // 6: opencode.orchestrator.v1.GetSessionResponse.session:type_name -> opencode.orchestrator.v1.Session
	15, // 7: opencode.orchestrator.v1.ListSessionsResponse.sessions:type_name -> opencode.orchestrator.v1.Session
	21, // 8: opencode.orchestrator.v1.ProxyHTTPRequest.headers:type_name -> opencode.orchestrator.v1.ProxyHTTPRequest.HeadersEntry
	22, // 9: opencode.orchestrator.v1.ProxyHTTPResponse.headers:type_name -> opencode.orchestrator.v1.ProxyHTTPResponse.HeadersEntry
	0,  // 10: opencode.orchestrator.v1.Session.state:type_name -> opencode.orchestrator.v1.SessionState
	16, // 11: opencode.orchestrator.v1.Session.config:type_name -> opencode.orchestrator.v1.SessionConfig
	18, // 12: opencode.orchestrator.v1.Session.status:type_name -> opencode.orchestrator.v1.SessionStatus
	23, // 13: opencode.orchestrator.v1.Session.labels:type_name -> opencode.orchestrator.v1.Session.LabelsEntry
	25, // 14: opencode.orchestrator.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	25, // 15: opencode.orchestrator.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	25, // 16: opencode.orchestrator.v1.Session.last_accessed:type_name -> google.protobuf.Timestamp
	17, // 17: opencode.orchestrator.v1.SessionConfig.repository:type_name -> opencode.orchestrator.v1.RepositoryConfig
	24, // 18: opencode.orchestrator.v1.SessionConfig.environment:type_name -> opencode.orchestrator.v1.SessionConfig.EnvironmentEntry
	25, // 19: opencode.orchestrator.v1.SessionStatus.ready_at:type_name -> google.protobuf.Timestamp
	2,  // 20: opencode.orchestrator.v1.OrchestratorService.Health:input_type -> opencode.orchestrator.v1.HealthRequest
	4,  // 21: opencode.orchestrator.v1.OrchestratorService.CreateSession:input_type -> opencode.orchestrator.v1.CreateSessionRequest
	6,  // 22: opencode.orchestrator.v1.OrchestratorService.GetSession:input_type -> opencode.orchestrator.v1.GetSessionRequest
	8,  // 23: opencode.orchestrator.v1.OrchestratorService.ListSessions:input_type -> opencode.orchestrator.v1.ListSessionsRequest
	10, // 24: opencode.orchestrator.v1.OrchestratorService.DeleteSession:input_type -> opencode.orchestrator.v1.DeleteSessionRequest
	11, // 25: opencode.orchestrator.v1.OrchestratorService.ProxyHTTP:input_type -> opencode.orchestrator.v1.ProxyHTTPRequest
	13, // 26: opencode.orchestrator.v1.OrchestratorService.ProxyStream:input_type -> opencode.orchestrator.v1.ProxyStreamRequest
	3,  // 27: opencode.orchestrator.v1.OrchestratorService.Health:output_type -> opencode.orchestrator.v1.HealthResponse
	5,  // 28: opencode.orchestrator.v1.OrchestratorService.CreateSession:output_type -> opencode.orchestrator.v1.CreateSessionResponse
	7,  // 29: opencode.orchestrator.v1.OrchestratorService.GetSession:output_type -> opencode.orchestrator.v1.GetSessionResponse
	9,  // 30: opencode.orchestrator.v1.OrchestratorService.ListSessions:output_type -> opencode.orchestrator.v1.ListSessionsResponse
	26, // 31: opencode.orchestrator.v1.OrchestratorService.DeleteSession:output_type -> google.protobuf.Empty
	12, // 32: opencode.orchestrator.v1.OrchestratorService.ProxyHTTP:output_type -> opencode.orchestrator.v1.ProxyHTTPResponse
	14, // 33: opencode.orchestrator.v1.OrchestratorService.ProxyStream:output_type -> opencode.orchestrator.v1.ProxyStreamResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_orchestrator_v1_orchestrator_proto_init() }
func file_orchestrator_v1_orchestrator_proto_init() {
	if File_orchestrator_v1_orchestrator_proto != nil {
		return
	}
	file_orchestrator_v1_orchestrator_proto_msgTypes[11].OneofWrappers = []any{
		(*ProxyStreamRequest_Data)(nil),
		(*ProxyStreamRequest_Control)(nil),
	}
	file_orchestrator_v1_orchestrator_proto_msgTypes[12].OneofWrappers = []any{
		(*ProxyStreamResponse_Data)(nil),
		(*ProxyStreamResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_v1_orchestrator_proto_rawDesc), len(file_orchestrator_v1_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_v1_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_v1_orchestrator_proto_depIdxs,
		EnumInfos:         file_orchestrator_v1_orchestrator_proto_enumTypes,
		MessageInfos:      file_orchestrator_v1_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_v1_orchestrator_proto = out.File
	file_orchestrator_v1_orchestrator_proto_goTypes = nil
	file_orchestrator_v1_orchestrator_proto_depIdxs = nil
}
